### PR TITLE
Adding a standard README template in markdown

### PR DESCRIPTION
**Pull request by beelandc**

### CODE REVIEW

**Review by kamiyokamiru — APPROVED** [review]
Great template. Thanks!

**Review by kamiyokamiru — CHANGES_REQUESTED** [review]
Change Python version used from 3.5 to 3.6 in README.md file

**Comment by beelandc** [comment]
Done

**Review by kamiyokamiru — DISMISSED** [review]

**Comment by gjz999gitit** [comment]
test

**Review by gjz999gitit — CHANGES_REQUESTED** [review]
Change Django to 2.1.2

**Review by kamiyokamiru — APPROVED** [review]

**Review by gjz999gitit — APPROVED** [review]

**Pull request merged**
