### PR TITLE
Updated file upload logic and added very basic view tests

### PR DESCRIPTION
**Pull request by beelandc**

### CODE REVIEW

**Review by kamiyokamiru — DISMISSED** [review]

**Comment by beelandc** [comment]
Oops, I thought I was doing this on a different branch... let me see if I can back that commit out somehow

**Comment by beelandc** [comment]
Ok, I reverted that commit on my master branch, so this should be back to what it was before my WIP commit. Sorry to force a re-review

**Review by kamiyokamiru — APPROVED** [review]

**Comment by gjz999gitit** [comment]
approved

**Review by gjz999gitit — APPROVED** [review]
approved

**Pull request merged**
