### PR TITLE
Updates to fix PhotoTagger integration; Updated requests module version

### PR DESCRIPTION
**Pull request by beelandc**
Updated PhotoTagger API integration logic to work with updated Classify/ interface
Updated requests module version to mitigate security vulnerability;

### CODE REVIEW

**Review by kamiyokamiru — DISMISSED** [review]
Ok ^^

**Comment by beelandc** [comment]
Sorry, just pushed up one more commit to remove some print statements that I accidentally left in, etc

**Review by kamiyokamiru — APPROVED** [review]
Ok ^^

**Review by gjz999gitit — APPROVED** [review]
Approve

**Pull request merged**
